/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exercise_202;

/**
 *
 * @author kilia
 */
public class RadioGUI extends javax.swing.JFrame {

    /**
     * Creates new form RadioGUI
     */
    private SenderTableModel model = new SenderTableModel();
    public RadioGUI() {
        initComponents();
        tbRadio.setModel(model);
        tbRadio.setDefaultRenderer(Object.class, new SenderTableRenderer());
        tbRadio.setComponentPopupMenu(jPopupMenu1);
        model.add(new Sender("Oe3", 33.21, Sender.Band.AM));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        miHinzufügen = new javax.swing.JMenuItem();
        miVerstecken = new javax.swing.JMenuItem();
        miAnzeigen = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbRadio = new javax.swing.JTable();

        miHinzufügen.setText("Hinzufügen");
        miHinzufügen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miHinzufügenActionPerformed(evt);
            }
        });
        jPopupMenu1.add(miHinzufügen);

        miVerstecken.setText("Band verstecken");
        miVerstecken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVersteckenActionPerformed(evt);
            }
        });
        jPopupMenu1.add(miVerstecken);

        miAnzeigen.setText("Band anzeigen");
        miAnzeigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAnzeigenActionPerformed(evt);
            }
        });
        jPopupMenu1.add(miAnzeigen);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        tbRadio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbRadio);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miHinzufügenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miHinzufügenActionPerformed
        SenderDlg dialog = new SenderDlg(this, true);
        dialog.setVisible(true);
        if(dialog.isOk()){
            model.add(dialog.getSender());
        }
    }//GEN-LAST:event_miHinzufügenActionPerformed

    private void miVersteckenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVersteckenActionPerformed
        model.hideBand();
    }//GEN-LAST:event_miVersteckenActionPerformed

    private void miAnzeigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAnzeigenActionPerformed
        model.showBand();
    }//GEN-LAST:event_miAnzeigenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RadioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RadioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RadioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RadioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RadioGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem miAnzeigen;
    private javax.swing.JMenuItem miHinzufügen;
    private javax.swing.JMenuItem miVerstecken;
    private javax.swing.JTable tbRadio;
    // End of variables declaration//GEN-END:variables
}
